kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "multiproject-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/avoigtma/my-openshift-examples"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/multiproject-jenkins/Jenkinsfile
