apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: centos-diskperftools
  name: centos-diskperftools
spec:
  output:
    to:
      kind: ImageStreamTag
      name: centos-diskperftools:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/avoigtma/my-openshift-examples.git
    contextDir: dockerbuilds/docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel.sampleCustomDocker.docker
      from:
        kind: ImageStreamTag
        name: centos:latest
        namespace: openshift
      noCache: true
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
