apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: sampleCustomDocker
  name: sampleCustomDocker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: sampleCustomDocker:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/avoigtma/my-openshift-examples.git
    contextDir: dockerbuilds/docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel.sampleCustomDocker.docker
      from:
        kind: ImageStreamTag
        name: rhel7:latest
        namespace: openshift
      noCache: true
  triggers:
  - generic:
      secret: OpBJjE82Iz-1B5f9q7zz
    type: Generic
  - imageChange:
    type: ImageChange
  - type: ConfigChange
