apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: sample-custom-docker-ubi
  name: sample-custom-docker-ubi
spec:
  output:
    to:
      kind: ImageStreamTag
      name: sample-custom-docker-ubi:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/avoigtma/my-openshift-examples.git
    contextDir: dockerbuilds/docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel-ubi.sampleCustomDocker.docker
      from:
        kind: ImageStreamTag
        name: ubi:latest
        namespace: openshift
      noCache: true
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
