apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: sample-docker-ubi
    deploymentconfig: sample-docker-ubi
  name: sample-docker-ubi
spec:
  replicas: 1
  selector:
    name: sample-docker-ubi
  strategy:
    type: Rolling
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      name: sample-docker-ubi
      labels:
        name: sample-docker-ubi
    spec:
      containers:
        - env:
            - name: MY_SAMPLE_ENV_VAR
              value: 'test-value'
          image: sample-custom-docker-ubi:latest
          imagePullPolicy: IfNotPresent
          name: sample-docker-ubi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - sample-docker-ubi
        from:
          kind: ImageStreamTag
          name: 'sample-custom-docker-ubi:latest'
    - type: ConfigChange
