apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: centos-diskperftools
    deploymentconfig: centos-diskperftools
  name: centos-diskperftools
spec:
  replicas: 1
  selector:
    name: centos-diskperftools
  strategy:
    type: Rolling
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      name: centos-diskperftools
      labels:
        name: centos-diskperftools
    spec:
      containers:
        - image: centos-diskperftools:latest
          imagePullPolicy: IfNotPresent
          name: centos-diskperftools
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - centos-diskperftools
        from:
          kind: ImageStreamTag
          name: 'centos-diskperftools:latest'
    - type: ConfigChange
