apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rsyslog-rhel-ubi
    deploymentconfig: rsyslog-rhel-ubi
  name: rsyslog-rhel-ubi
spec:
  replicas: 1
  selector:
    name: rsyslog-rhel-ubi
  strategy:
    type: Rolling
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      name: rsyslog-rhel-ubi
      labels:
        name: rsyslog-rhel-ubi
    spec:
      containers:
        - env:
            - name: MY_SAMPLE_ENV_VAR
              value: 'test-value'
          image: rsyslog-rhel-ubi:latest
          imagePullPolicy: IfNotPresent
          name: rsyslog-rhel-ubi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - rsyslog-rhel-ubi
        from:
          kind: ImageStreamTag
          name: rsyslog-rhel-ubi:latest
    - type: ConfigChange
