apiVersion: v1
kind: Template
labels:
  template: nginx-application-template
message: For more information about using this template, including OpenShift considerations,
  see the documentation (TODO).
metadata:
  annotations:
    description: This templates performs the basic setup for applications.
    iconClass: icon-nginx
    openshift.io/display-name: NGINX Application Template
    template.openshift.io/documentation-url: TODO
    template.openshift.io/long-description: This template defines resources needed
      to develop an application, including a build configuration, application deployment
      configuration.
    template.openshift.io/provider-display-name: TODO
    template.openshift.io/support-url: TODO
  name: nginx-application-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    successfulBuildsHistoryLimit: ${BUILD_SUCCESSFULBUILDSHISTORYLIMIT}
    failedBuildsHistoryLimit: ${BUILD_FAILEDBUILDSHISTORYLIMIT}
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: ${GIT_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: rhscl_nginx-112-rhel7:latest
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${REGISTRY}/${NAMESPACE}/${APPLICATION}:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    replicas: ${INITIAL_REPLICAS}
    selector:
      deploymentconfig: ${APPLICATION}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION}
          deploymentconfig: ${APPLICATION}
      spec:
        containers:
        - image: ${REGISTRY}/${NAMESPACE}/${APPLICATION}:latest
          imagePullPolicy: Always
          name: ${APPLICATION}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: ${RESOURCE_CPU_LIMITS}
              memory: ${RESOURCE_MEM_LIMITS}
            requests:
              cpu: ${RESOURCE_CPU_REQUESTS}
              memory: ${RESOURCE_MEM_REQUESTS}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION}:latest
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    host: ${APPLICATION}-${NAMESPACE}.${APPLICATION_DOMAIN}
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APPLICATION}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
  spec:
    maxReplicas: ${HPA_MAX_REPLICAS}
    minReplicas: ${HPA_MIN_REPLICAS}
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${APPLICATION}
    targetCPUUtilizationPercentage: ${HPA_CPU_UTIL_PERCENTAGE}
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: ${APPLICATION}
  spec:
    selector:
      matchLabels:
        app: ${APPLICATION}
    minAvailable: 2
parameters:
- description: The name of the cluster central namespace.
  displayName: Central Namespace
  name: CENTRAL_NAMESPACE
  required: true
  value: openshift
- description: The name of the application project / OpenShift namespace.
  displayName: The name of the application project / OpenShift namespace.
  name: NAMESPACE
  required: true
- description: The name of the application.
  displayName: Application
  name: APPLICATION
  required: true
  value: ${APPLICATION}
- description: The exposed hostname that will route to the application's service,
    if left blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: The GIT URL for the source code used in the application build
  displayName: Git URL
  name: GIT_URL
  required: true
- description: The registry URL; defaults to OpenShift internal registry service name/port ('docker-registry.default.svc:5000'); for 'minishift' use '172.30.1.1:5000'
  displayName: Registry URL
  name: REGISTRY
  required: true
  value: docker-registry.default.svc:5000
- description: Initial numbers of replicas
  displayName: (Initial) Number of Replicas
  name: INITIAL_REPLICAS
  value: '2'
- description: Build pruning - successfulBuildsHistoryLimit
  displayName: Build pruning - successfulBuildsHistoryLimit
  name: BUILD_SUCCESSFULBUILDSHISTORYLIMIT
  value: '5'
- description: Build pruning - failedBuildsHistoryLimit
  displayName: Build pruning - failedBuildsHistoryLimit
  name: BUILD_FAILEDBUILDSHISTORYLIMIT
  value: '5'
- description: Resource limits - cpu - requests
  displayName: Resource limits - cpu - requests
  name: RESOURCE_CPU_REQUESTS
  value: 200m
- description: Resource limits - cpu - limits
  displayName: Resource limits - cpu - limits
  name: RESOURCE_CPU_LIMITS
  value: '1'
- description: Resource limits - memory - requests
  displayName: Resource limits - memory - requests
  name: RESOURCE_MEM_REQUESTS
  value: 50Mi
- description: Resource limits - memory - limits
  displayName: Resource limits - memory - limits
  name: RESOURCE_MEM_LIMITS
  value: 1000Mi
- description: Autoscale min replicas
  displayName: Autoscale min replicas
  name: HPA_MIN_REPLICAS
  value: '2'
- description: Autoscale max replicas
  displayName: Autoscale max replicas
  name: HPA_MAX_REPLICAS
  value: '5'
- description: Autoscale CPU Utilization Percentage
  displayName: Autoscale CPU Utilization Percentage
  name: HPA_CPU_UTIL_PERCENTAGE
  value: '70'
