apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user capable of performing monitoring activities for an OpenShift cluster
    openshift.io/reconcile-protect: "false"
  name: monitoring-role
rules:
- apiGroups:
  - "events.k8s.io"
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes/stats
  - nodes/status
  - nodes/metrics
  - nodes/spec
  verbs:
  - get
## unclear: do we need create for 'nodes/stats' like cluster-reader ??
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - resourcequotausages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "route.openshift.io"
  attributeRestrictions: null
  resources:
  - routes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "build.openshift.io"
  attributeRestrictions: null
  resources:
  - buildlogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "image.openshift.io"
  attributeRestrictions: null
  resources:
  - imagestreams/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods/status
  verbs:
  - get
- nonResourceURLs:
  - "/metrics"
  attributeRestrictions: null
  resources:
  - ""
  verbs:
  - get

