apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user capable of traversing namespaces and accessing (read-only) route objects in all namespaces
    openshift.io/reconcile-protect: "false"
  name: route-cluster-reader-role
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - "route.openshift.io"
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list

