kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nodejs-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/avoigtma/my-openshift-examples"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/nodejs-jenkins/Jenkinsfile
